# Generated by Django 4.1.1 on 2022-10-26 16:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutHistory',
            fields=[
                ('user', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('user', models.CharField(max_length=50)),
                ('reffering_workouthistory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.workouthistory')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('BP', 'Bench Press'), ('DL', 'Deadlift'), ('OHP', 'Overhead Press')], max_length=50)),
                ('reps', models.PositiveIntegerField()),
                ('sets', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('rpe', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('reffering_workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.workout')),
            ],
        ),
    ]
