# Generated by Django 4.1.1 on 2022-11-23 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalorieHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(choices=[('BP', 'Bench Press'), ('DL', 'Deadlift'), ('OHP', 'Overhead Press'), ('FS', 'Front Squat'), ('PU', 'Pullup'), ('RDL', 'Romanian Deadlift'), ('DOP', 'Dumbbell Overhead Press'), ('HPT', 'Hip Thrust'), ('SQT', 'Squat')], max_length=50),
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('user', models.CharField(max_length=50)),
                ('reffering_caloriehistory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.caloriehistory')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('breakfast', 'breakfast'), ('lunch', 'lunch'), ('dinner', 'dinner'), ('snacks', 'snacks')], max_length=50)),
                ('carbohydrate', models.PositiveIntegerField()),
                ('fats', models.PositiveIntegerField()),
                ('protein', models.PositiveIntegerField()),
                ('calorie', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('reffering_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.day')),
            ],
        ),
    ]
